tap "caskroom/fonts"
tap "caskroom/versions"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "sbdchd/macchanger"
cask "java"
brew "ant"
brew "openssl"
brew "atool"
brew "awscli"
brew "bash"
brew "bat"
brew "rlwrap"
brew "clojure"
brew "cmatrix"
brew "coreutils"
brew "defaultbrowser"
brew "dockutil"
brew "dos2unix"
brew "duti"
brew "emacs"
brew "eye-d3"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "imagemagick"
brew "gifify"
brew "gifsicle"
brew "git"
brew "gnu-sed"
brew "go"
brew "grep"
brew "iftop"
brew "leiningen"
brew "locateme"
brew "mackup"
brew "mas"
brew "python@2"
brew "mongodb"
brew "mp3cat"
brew "mp3check"
brew "mp3info"
brew "mp3val"
brew "mp3wrap"
brew "mpck"
brew "mysql"
brew "node"
brew "osx-dictionary", args: ["HEAD"]
brew "php"
brew "pkg-config"
brew "prettier"
brew "psutils"
brew "r"
brew "redis"
brew "rsync"
brew "safe-rm"
brew "screenfetch"
brew "shellcheck"
brew "sphinx-doc"
brew "sshguard", restart_service: true
brew "tmux"
brew "trash"
brew "tree"
brew "wget"
brew "whatmp3"
brew "sbdchd/macchanger/macchanger"
cask "appzapper"
cask "balenaetcher"
cask "boom"
cask "boom-3d"
cask "calibre"
cask "docker"
cask "drawio"
cask "firefox"
cask "geektool"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "keka"
cask "marshallofsound-google-play-music-player"
cask "mysqlworkbench"
cask "netbeans"
cask "origami-studio"
cask "postman"
cask "signal"
cask "spotify"
cask "ssh-tunnel-manager"
cask "steam"
cask "tidal"
cask "tor-browser"
cask "transmission"
cask "unlox"
cask "visual-studio-code"
cask "vlc"
cask "vox"
cask "xquartz"
cask "caskroom/fonts/font-awesome-terminal-fonts"
cask "caskroom/fonts/font-lato"
cask "caskroom/fonts/font-open-sans"
cask "caskroom/fonts/font-roboto"
cask "caskroom/fonts/font-source-code-pro"
cask "caskroom/fonts/font-source-code-pro-for-powerline"
cask "caskroom/fonts/font-source-sans-pro"
cask "caskroom/fonts/font-source-serif-pro"
mas "1Password 7", id: 1333542190
mas "Dr. Cleaner", id: 921458519
mas "GravitDesigner", id: 1207744923
mas "Memory Clean", id: 451444120
mas "myHomework", id: 970610831
mas "Parcel", id: 639968404
mas "PhotoScape X", id: 929507092
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "System Designer", id: 1102494854
mas "TextWrangler", id: 404010395
mas "Trello", id: 1278508951
mas "TweetDeck", id: 485812721
mas "Twitterrific", id: 1289378661
mas "VirtualDJ Home", id: 417934534
mas "Xcode", id: 497799835
